### ISSUE TITLE
If no processes are selected for any sliders, closing the main window fails

### ISSUE THREAD

**Issue by ngc6027** [Narfjones/CTRLDeck#6]
Error is:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python39\lib\tkinter\__init__.py", line 1885, in __call__
    return self.func(*args)
  File "D:\learn_code_vbox_share\CTRLDeck-Python\CTRLDeck_Python.py", line 202, in hide_window
    sliderProcesses.append(str(serialValuetoVolume.sliderProcesses[i]))
TypeError: 'NoneType' object is not subscriptable
```

**Comment by Narfjones** [comment]
Was a catch on trying to assign the slider name to the right-click menu on the system tray icon.

Added a try/except to display the message "No process chosen"
