### ISSUE TITLE
Logging Error: Comtypes

### ISSUE THREAD

**Issue by Narfjones** [Narfjones/CTRLDeck#8]
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\logging\__init__.py", line 1029, in emit
    self.flush()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\logging\__init__.py", line 1009, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='C:\\Users\\Bj\\Documents\\GitHub\\CTRLDeck-Python\\ctrldeck.log'>
Call stack:
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\Bj\Documents\GitHub\CTRLDeck-Python\CTRLDeck_Python.py", line 150, in sliderRun
    serialValuetoVolume.getValues()
  File "c:\Users\Bj\Documents\GitHub\CTRLDeck-Python\inc\serialValuetoVolume.py", line 185, in getValues
    getSessionsSpeakers()
  File "c:\Users\Bj\Documents\GitHub\CTRLDeck-Python\inc\serialValuetoVolume.py", line 102, in getSessionsSpeakers
    sessions = AudioUtilities.GetAllSessions() # Scans sessions and locates the one with a name matching the sliderProcess
  File "C:\Users\Bj\AppData\Roaming\Python\Python37\site-packages\comtypes\__init__.py", line 956, in __del__
    _debug("Release %s", self)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\logging\__init__.py", line 1366, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\logging\__init__.py", line 1514, in _log
    self.handle(record)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\logging\__init__.py", line 1524, in handle
    self.callHandlers(record)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\logging\__init__.py", line 1586, in callHandlers
    hdlr.handle(record)
    self.emit(record)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\logging\__init__.py", line 1127, in emit
    StreamHandler.emit(self, record)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\logging\__init__.py", line 1029, in emit
    self.flush()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\logging\__init__.py", line 1009, in flush
    self.stream.flush()
  File "C:\Users\Bj\AppData\Roaming\Python\Python37\site-packages\comtypes\__init__.py", line 956, in __del__
    _debug("Release %s", self)
Message: 'Release %s'
Arguments: (<POINTER(IUnknown) ptr=0x2957ec3ba30 at 29516e6e848>,)

**Comment by Narfjones** [comment]
Tentatively resolved. It seems that there were conflicts between the software and the comtypes backend accessing the log file at the same time. Raised the log type to WARNING and raised error logs to WARNING level. There is no more file access conflict.
